### PR TITLE
undefined error fix

### PR DESCRIPTION
**Pull request by jfdnc**
undefined error thrown for "term" at reverse.js line 246. fixed by adding let declaration.

### CODE REVIEW

**Review by Pomax — CHANGES_REQUESTED** [review]
can you add `term` to the list above so it's just a one-time allocation? Other than that: nice catch!

**Review by jfdnc — COMMENTED** [review]
Updated per comments on first commit

**Comment by Pomax** [comment]
I'd love to know why you moved all the other declarations around though. At first I thought you sorted them alphabetically, but that's not actually the case. Why is the diff so much more than just a single line insert in the block of variables? =)

**Comment by Pomax** [comment]
mirrored in https://github.com/Pomax/svg-path-reverse/blob/gh-pages/reverse.js (but without the variable shuffling).

**Comment by Pomax** [comment]
Thanks for the PR though!

**Comment by jfdnc** [comment]
Because mixing undefined variables and defined variables at the top of a function scope decreases readability and is bad form. Thanks.

**Comment by Pomax** [comment]
I guess that depends on whether you use a text editor (like sublime) or an IDE (like eclipse). Or something in between (like Visual Studio Code) that still does declaration/use tracking.

I've left sublime for that reason recently in favour of VS Code, since it does a way better job at highlighting things like this.

**Pull request closed without merging**
